name: Laravel CI/CD

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때마다 실행

jobs:
  deploy:
    runs-on: ubuntu-latest  # Ubuntu 환경에서 실행

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # GitHub 저장소에서 코드 체크아웃

      - name: Set up SSH key
        run: |
          # PEM 키를 EC2_SSH_KEY Secret에서 받아서 사용
          mkdir -p ~/.ssh
          echo "$EC2_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add EC2 server to known_hosts
        run: |
          # EC2 서버의 호스트 키를 known_hosts에 추가하여 SSH 연결 시 경고 방지
          ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          echo "Deploying to EC2..."
          # SSH로 EC2에 접속하여 배포 작업을 진행
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            cd /home/ubuntu/event
            git pull origin main
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
            sudo systemctl restart nginx
          EOF
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
